# Generated by Django 5.0.4 on 2024-04-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_brand',
            field=models.FileField(upload_to='brand/'),
        ),
    ]
