# Generated by Django 5.0.4 on 2024-04-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_brand_logo_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='rating_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rating'),
        ),
    ]
