# Generated by Django 5.0.4 on 2024-04-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_device_rating_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='rating_device',
        ),
    ]
