# Generated by Django 5.0.4 on 2024-05-11 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_device_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='device',
        ),
        migrations.CreateModel(
            name='BasketDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.basket')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
    ]
