# Generated by Django 5.0.4 on 2024-05-11 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_basket_device_basketdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketdevice',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.basket', unique=True),
        ),
    ]
