# Generated by Django 5.0.4 on 2024-05-17 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_status_typeorder_order_deliveryorder_orderdevice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketdevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='api.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='orderdevice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_devices', to='api.order'),
        ),
    ]
