# Generated by Django 5.0.4 on 2024-05-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_basketdevice_device_alter_deliveryorder_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketdevice',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
