# Generated by Django 5.0.4 on 2024-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_basketdevice_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdevice',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
