# Generated by Django 5.0.4 on 2024-06-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(default='user/default_user.svg', upload_to='type/'),
        ),
    ]
