# Generated by Django 5.0.4 on 2024-06-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_deliveryorder_date_delivery_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='api.type')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.characteristic')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='api.device')),
            ],
        ),
    ]
