# Generated by Django 5.0.4 on 2024-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_characteristic_devicecharacteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
