version: '3.3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "sm4u"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "28138415"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: sm4u
      DB_USER: postgres
      DB_PASSWORD: 28138415


  frontend:
   build:
     context: ./frontend
   volumes:
     - ./frontend:/app
   ports:
     - "127.0.0.1:3000:3000"
   environment:
     - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
