version: '4.31.1'

services:
  db:
    build:
      context: ./postgres
    environment:
      POSTGRES_DB: sm4u
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - postgres_data:/var/lib/postgresql/data
      

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: sm4u
      DB_USER: postgres
      DB_PASSWORD: 1234

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

volumes:
  postgres_data: